### ISSUE TITLE
mtm6201_010_ final- issues banners and navi 

### ISSUE THREAD

**Issue by coop0162** [coop0162/mtm6201_final#5]
@abhaysharma

Line 61 to 70 top main banner is interfering with navibar ( not responsive  and do I fix it ?

linw 93 to 102 second banner how to shrink?

**Comment by abhaysharma** [comment]
@coop0162 I do not see the issue with the top banner, do you mean it moves down when the hamburger navigation is opened? If so, this is the expected behaviour.

The logos under the main banner should be added as individual images and not one long image. You will need to add 3 images in separate divs that have the layout classes assigned to them, such as div.col-md > img three times inside a div.row
